//
//  MapShowViewController.swift
//  AriyaHouseITDemo
//
//  Created by msm72 on 29.08.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol MapShowDisplayLogic: class {
    func displayLocationInMap(fromViewModel viewModel: MapShowModels.Something.ViewModel)
}

class MapShowViewController: UIViewController {
    // MARK: - Properties
    var interactor: MapShowBusinessLogic?
    var router: (NSObjectProtocol & MapShowRoutingLogic & MapShowDataPassing)?
    var marker: GMSMarker?
    
    // MARK: - IBOutlets
    // @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var mapView: GMSMapView!

    
    // MARK: - Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        setup()
    }
    
    
    // MARK: - Setup
    private func setup() {
        let viewController  =   self
        let interactor      =   MapShowInteractor()
        let presenter       =   MapShowPresenter()
        let router          =   MapShowRouter()
        
        viewController.interactor   =   interactor
        viewController.router       =   router
        interactor.presenter        =   presenter
        presenter.viewController    =   viewController
        router.viewController       =   viewController
        router.dataStore            =   interactor
    }
    
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewSettingsDidLoad()
    }
    
    
    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        let requestModel = MapShowModels.Something.RequestModel()
        
        interactor?.loadLocationInMap(fromRequestModel: requestModel)
        
        // Setup Google Map
        mapView.isMyLocationEnabled = true
        mapView.settings.myLocationButton = true
    }
}


// MARK: - MapShowDisplayLogic
extension MapShowViewController: MapShowDisplayLogic {
    func displayLocationInMap(fromViewModel viewModel: MapShowModels.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        self.mapView.camera = GMSCameraPosition(target: viewModel.coordinate, zoom: 15, bearing: 0, viewingAngle: 0)
        
        // Add custom marker
        if (!viewModel.isVerified) {
            self.marker = GMSMarker(position: viewModel.coordinate)
            self.marker!.map = mapView
            self.marker!.icon = GMSMarker.markerImage(with: .green)
        }
    }
}
