//
//  MapShowInteractor.swift
//  AriyaHouseITDemo
//
//  Created by msm72 on 29.08.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol MapShowBusinessLogic {
    func doSomething(request: MapShowModels.Something.RequestModel)
}

protocol MapShowDataStore {
    //var name: String { get set }
}

class MapShowInteractor: MapShowBusinessLogic, MapShowDataStore {
    // MARK: - Properties
    var presenter: MapShowPresentationLogic?
    var worker: MapShowWorker?
    //var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(request: MapShowModels.Something.RequestModel) {
        worker = MapShowWorker()
        worker?.doSomeWork()
        
        let responseModel = MapShowModels.Something.ResponseModel()
        presenter?.presentSomething(response: responseModel)
    }
}
