//
//  MapShowInteractor.swift
//  AriyaHouseITDemo
//
//  Created by msm72 on 29.08.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol MapShowBusinessLogic {
    func loadLocationInMap(fromRequestModel requestModel: MapShowModels.Something.RequestModel)
}

protocol MapShowDataStore {
    // var name: String { get set }
}

class MapShowInteractor: MapShowBusinessLogic, MapShowDataStore {
    // MARK: - Properties
    var presenter: MapShowPresentationLogic?
    var worker: MapShowWorker?
    // var name: String = ""
    let locationManager = MSMLocationManager()
    
    
    // MARK: - Business logic implementation
    func loadLocationInMap(fromRequestModel requestModel: MapShowModels.Something.RequestModel) {
        worker = MapShowWorker()
        worker?.doSomeWork()
        
        // Start MSMLocationManager
        locationManager.startCoreLocation()
        
        // Search location
        locationManager.handlerLocationCompletion = { _ in
            let coordinate = CLLocationCoordinate2D.init(latitude: self.locationManager.currentLocation.latitude!,
                                                         longitude: self.locationManager.currentLocation.longitude!)
            
            let responseModel = MapShowModels.Something.ResponseModel(coordinate: coordinate, isVerified: self.locationManager.currentLocation.isVerified)
            self.presenter?.prepareDisplayLocationInMap(fromResponseModel: responseModel)
        }
    }
}
